language: cpp

compiler: 
  - gcc
  - clang

branches:
  only:
    - master

addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.6
      #- llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - libpapi-dev
    - libconfig++8-dev
    - gdb
    - gcc-5
    - g++-5
    - gcc-5-multilib
    - g++-5-multilib
    - llvm-3.6
    - llvm-3.6-dev
      #- llvm-3.7
      #- llvm-3.7-dev
      #- llvm-3.8
      #- llvm-3.8-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-5"; export CXX="g++-5"; fi

os:
  - linux

script: 
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
