nguage: cpp
compiler:
  - clang
script: rake
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-dev
before_script:
  - mkdir build 
  - cd build
  - cmake ..
script: make
branches:
  only:
    - master
  notifications:
    email:
      recipients:
        - vandersonmr2@gmail.com
      on_success: change
      on_failure: always
os:
  - linux
