language: cpp

env:
  - LLVMVER=3.6

compiler: 
  - gcc

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - libc6
    - multiarch-support 
    - libconfig++8-dev
    - gdb
    - clang-3.6
    - clang-3.6-dev
    - gcc-5
    - g++-5
    - gcc-5-multilib
    - g++-5-multilib
    - llvm-3.6
    - llvm-3.6-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CC="gcc-5"; export CXX="g++-5"; fi

os:
  - linux

script: 
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/libp/libpfm4/libpfm4_4.4.0+git47-g71166e2-1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/p/papi/libpapi5.3_5.3.0-3_amd64.deb 
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/p/papi/libpapi-dev_5.3.0-3_amd64.deb
  - sudo dpkg -i *.deb
  - sudo apt-get install -qq cmake
  - PATH=/usr/lib/llvm-3.6/bin:$PATH
  - llvm-config --version
  - mkdir build
  - cd build
  - cmake ..
  - make -j4

notifications:
  email:
    on_success: never
    on_failure: never
