GEOS - Guide for Exploration of the Optimization Space: lru::cache< K, V > Class Template Reference
lru::cache< K, V > Class Template Reference
#include <LRUCache.h>
Public Types
using key_type = K
using value_type = V
Public Member Functions
cache (const std::initializer_list< K > &&list={})
cache (const std::initializer_list< std::pair< K, V >> &&list)
void resize (size_t nth)
list_t::iterator find (const K &k)
list_t::iterator insert (const K &k, const V &v)
list_t::iterator insert (const V &v)
void erase (const K &k)
V & operator[] (const K &k)
const V & operator[] (const K &k) const
Friends
template<typename ostream >
ostream & operator<< (ostream &os, const cache &self)
Detailed Description
template<typename K, typename V = K>
class lru::cache< K, V >
Definition at line 15 of file LRUCache.h.
Member Typedef Documentation
template<typename K, typename V = K> using lru::cache< K, V >::key_type = K
Definition at line 21 of file LRUCache.h.
template<typename K, typename V = K> using lru::cache< K, V >::value_type = V
Definition at line 22 of file LRUCache.h.
Constructor & Destructor Documentation
template<typename K, typename V = K> lru::cache< K, V >::cache (const std::initializer_list< K > && list = {}) inline explicit
Definition at line 24 of file LRUCache.h.
template<typename K, typename V = K> lru::cache< K, V >::cache (const std::initializer_list< std::pair< K, V >> && list) inline
Definition at line 30 of file LRUCache.h.
Member Function Documentation
template<typename K, typename V = K> void lru::cache< K, V >::erase (const K & k) inline
Definition at line 76 of file LRUCache.h.
Referenced by lru::cache< unsigned >::erase(), lru::cache< unsigned >::insert(), and lru::cache< unsigned >::resize().
template<typename K, typename V = K> list_t::iterator lru::cache< K, V >::find (const K & k) inline
Definition at line 44 of file LRUCache.h.
Referenced by lru::cache< unsigned >::erase(), lru::cache< unsigned >::find(), lru::cache< unsigned >::insert(), and lru::cache< unsigned >::operator[]().
template<typename K, typename V = K> list_t::iterator lru::cache< K, V >::insert (const K & k, const V & v) inline
Definition at line 55 of file LRUCache.h.
Referenced by lru::cache< unsigned >::cache(), lru::cache< unsigned >::find(), lru::cache< unsigned >::insert(), and lru::cache< unsigned >::operator[]().
template<typename K, typename V = K> list_t::iterator lru::cache< K, V >::insert (const V & v) inline
Definition at line 73 of file LRUCache.h.
template<typename K, typename V = K> V& lru::cache< K, V >::operator[] (const K & k) inline
Definition at line 84 of file LRUCache.h.
template<typename K, typename V = K> const V& lru::cache< K, V >::operator[] (const K & k) const inline
Definition at line 93 of file LRUCache.h.
template<typename K, typename V = K> void lru::cache< K, V >::resize (size_t nth) inline
Definition at line 36 of file LRUCache.h.
Friends And Related Function Documentation
template<typename K, typename V = K> template<typename ostream > ostream& operator<< (ostream & os, const cache< K, V > & self) friend
Definition at line 97 of file LRUCache.h.
The documentation for this class was generated from the following file:
LRUCache.h