GEOS - Guide to Exploration of Otimization's Sequences: GEOS Class Reference
GEOS Class Reference
This class is responsable for apply passes into a ProfileModule, which contatains the LLVM code and the profiling information, and also analyse its execution time.
#include <GEOS.h>
Static Public Member Functions
static AnalysisMethod * getAnalyser (AnalysisMethodKind, llvm::StringRef)
Instantiates the specificated AnlysisMethod.
static llvm::Pass * getPass (OptimizationKind)
Returns the instanciation of the optimization choosed.
static ProfileModule * applyPassesOnFunction (llvm::StringRef, const ProfileModule &, llvm::FunctionPassManager &)
Like applyPasses this function apply a set of passes to the llvm module. However, it just apply those to an specific function.
static ProfileModule * applyPasses (const ProfileModule &, llvm::FunctionPassManager &)
Apply Passes (Transformations) into a ProfileModule. Also ensures that its profiling information ramains consistent. The ProfileModule given as parameter isn't modified, actualy all the modifications are made in a copy. This copy is returned as parameter.
static double analyseFunctionExecutionTime (llvm::StringRef, const ProfileModule &, AnalysisMethod *)
Estimate the execution time of a function from the ProfileModule with the given AnalysisMethod and returns it.
static double analyseExecutionTime (const ProfileModule &, AnalysisMethod *)
Estimate the execution time of a ProfileModule with the given AnalysisMethod and returns it.
Detailed Description
This class is responsable for apply passes into a ProfileModule, which contatains the LLVM code and the profiling information, and also analyse its execution time.
Definition at line 80 of file GEOS.h.
Member Function Documentation
double GEOS::analyseExecutionTime (const ProfileModule & PModule, AnalysisMethod * Analyser) static
Estimate the execution time of a ProfileModule with the given AnalysisMethod and returns it.
Definition at line 209 of file GEOS.cpp.
References AnalysisMethod::estimateExecutionTime(), ProfileModule::getLLVMModule(), and ProfileModule::getProfile().
Referenced by main().
double GEOS::analyseFunctionExecutionTime (llvm::StringRef , const ProfileModule & , AnalysisMethod *) static
Estimate the execution time of a function from the ProfileModule with the given AnalysisMethod and returns it.
Parameters
The first param is the name of the function that the analysis should be done.
Definition at line 190 of file GEOS.cpp.
References AnalysisMethod::estimateExecutionTime(), ProfileModule::getFunctionProfile(), and ProfileModule::getLLVMModule().
ProfileModule * GEOS::applyPasses (const ProfileModule & , llvm::FunctionPassManager &) static
Apply Passes (Transformations) into a ProfileModule. Also ensures that its profiling information ramains consistent. The ProfileModule given as parameter isn't modified, actualy all the modifications are made in a copy. This copy is returned as parameter.
Definition at line 179 of file GEOS.cpp.
References ProfileModule::getCopy(), and ProfileModule::getLLVMModule().
Referenced by main().
ProfileModule * GEOS::applyPassesOnFunction (llvm::StringRef , const ProfileModule & , llvm::FunctionPassManager &) static
Like applyPasses this function apply a set of passes to the llvm module. However, it just apply those to an specific function.
Parameters
the first param is the function name that the passes should be applied.
Definition at line 164 of file GEOS.cpp.
References ProfileModule::getCopy(), and ProfileModule::getLLVMModule().
Referenced by main().
AnalysisMethod * GEOS::getAnalyser (AnalysisMethodKind , llvm::StringRef) static
Instantiates the specificated AnlysisMethod.
Parameters
First is the AnalysisMethod kind and the second is the database file path.
Definition at line 26 of file GEOS.cpp.
References DatabaseFilename(), freqM, hashPlusInstM, hashWM, instCostM, instM, and randM.
Referenced by main().
Pass * GEOS::getPass (OptimizationKind OptChoosed) static
Returns the instanciation of the optimization choosed.
Definition at line 64 of file GEOS.cpp.
References AddDiscriminators, AggressiveDCE, AlignmentFromAssumptions, ConstantHoisting, ConstantPropagation, DeadCodeElimination, DeadInstElimination, EarlyCSE, GVN, InductionVariableSimplify, InstructionCombining, InstructionNamer, InstructionSimplifier, LCSSA, LICM, LowerAtomic, MemCpyOpt, MergedLoadStoreMotion, PromoteMemoryToRegister, Reassociate, ScalarReplAggregates, Sink, SROA, and ValuePropagation.
Referenced by main().
The documentation for this class was generated from the following files:
GEOS.h
GEOS.cpp