GEOS - Guide to Exploration of Otimization's Sequences: BBDescriptor Class Reference
BBDescriptor Class Reference
This class is responsible for representing BB's hashes in memory. It can be constructed by a string (hash representation in the file) or by a basic block that will serve as a base to create a new hash.
#include <BBDescriptor.h>
Public Member Functions
BBDescriptor ()
Create an empty hash.
BBDescriptor (llvm::BasicBlock &)
Create a hash for the Basic Block given as parameter.
BBDescriptor (const llvm::StringRef &)
Creates a memory representation of the hash from a string representation of the hash. Useful when loading the hash from a file.
void set (Descriptor, int)
set an information in the hash with a new value given as parameter.
void addUp (Descriptor, int n=1)
Sum 1 or n to the value of an information in the hash.
int getDescription (Descriptor)
get the value from an information in the hash.
llvm::StringRef getString ()
returns a string that represents this hash. For instance: "25-0-1-0-0-1-7-4-2-0-1-0-0-0-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1" Where each position represents the amount of something in the basic block. For example, in this case the first number is the number of instruction in the basic block. So this basic block had 25 instructions.
Static Public Member Functions
static double distance (BBDescriptor &, BBDescriptor &, bool Weight=false)
Calculates an Euclidian distance between two hashes.
Detailed Description
This class is responsible for representing BB's hashes in memory. It can be constructed by a string (hash representation in the file) or by a basic block that will serve as a base to create a new hash.
Definition at line 69 of file BBDescriptor.h.
Constructor & Destructor Documentation
BBDescriptor::BBDescriptor ()
Create an empty hash.
Definition at line 137 of file BBDescriptor.cpp.
BBDescriptor::BBDescriptor (llvm::BasicBlock &)
Create a hash for the Basic Block given as parameter.
BBDescriptor::BBDescriptor (const llvm::StringRef &)
Creates a memory representation of the hash from a string representation of the hash. Useful when loading the hash from a file.
Member Function Documentation
void BBDescriptor::addUp (Descriptor DescriptionId, int n = 1)
Sum 1 or n to the value of an information in the hash.
Definition at line 165 of file BBDescriptor.cpp.
double BBDescriptor::distance (BBDescriptor & a, BBDescriptor & b, bool Weight = false) static
Calculates an Euclidian distance between two hashes.
Parameters
weight when true it activates the use of weights for different information in the hash. The weight comes from the DescriptorWeight function.
Returns
it returns a double that represents how equally two basic blocks are.
Definition at line 182 of file BBDescriptor.cpp.
References getDescription().
Referenced by DatabaseManager::getNearest().
int BBDescriptor::getDescription (Descriptor DescriptionId)
get the value from an information in the hash.
Definition at line 169 of file BBDescriptor.cpp.
Referenced by distance().
StringRef BBDescriptor::getString ()
returns a string that represents this hash. For instance: "25-0-1-0-0-1-7-4-2-0-1-0-0-0-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1" Where each position represents the amount of something in the basic block. For example, in this case the first number is the number of instruction in the basic block. So this basic block had 25 instructions.
Definition at line 173 of file BBDescriptor.cpp.
Referenced by DatabaseManager::getTime(), and DatabaseManager::hasHash().
void BBDescriptor::set (Descriptor DescriptionId, int Value)
set an information in the hash with a new value given as parameter.
Definition at line 161 of file BBDescriptor.cpp.
References Value.
The documentation for this class was generated from the following files:
BBDescriptor.h
BBDescriptor.cpp