GEOS - Guide to Exploration of Otimization's Sequences: DatabaseManager Class Reference
DatabaseManager Class Reference
This class is responsible for loading and saving hashes databases. It is a representation in memory of a hash database and has functions to use and manipulate it.
#include <DatabaseManager.h>
Public Types
typedef std::unordered_map
< BBHash, double >::iterator iterator
typedef std::unordered_map
< BBHash, double >
::const_iterator const_iterator
Public Member Functions
DatabaseManager (llvm::StringRef)
Creates a database loading it from a file.
int size () const
Returns the number of different BB hashes which there are in the database.
double getTime (const BBHash &) const
Returns the execution time found in the database for the given Hash (BBDescritor).
bool hasHash (const BBHash &) const
Returns true if and only if there is an exactly equal hash on the database.
void insert (BBHash, double)
Insert a new value in the database.
void unionWith (DatabaseManager &)
This function merge the database with the one given as parameter.
void printDatabase () const
Prints all the database. Each new line contains a hash and its execution time separated by space.
BBHash * getNearest (const BBHash &) const
Returns the nearest BBHash from the given parameter in the database.
iterator begin ()
const_iterator cbegin () const
iterator end ()
const_iterator cend () const
Detailed Description
This class is responsible for loading and saving hashes databases. It is a representation in memory of a hash database and has functions to use and manipulate it.
Definition at line 22 of file DatabaseManager.h.
Member Typedef Documentation
typedef std::unordered_map<BBHash, double>:: const_iterator DatabaseManager::const_iterator
Definition at line 74 of file DatabaseManager.h.
typedef std::unordered_map<BBHash, double>::iterator DatabaseManager::iterator
Definition at line 72 of file DatabaseManager.h.
Constructor & Destructor Documentation
DatabaseManager::DatabaseManager (llvm::StringRef)
Creates a database loading it from a file.
Definition at line 61 of file DatabaseManager.cpp.
References BBHash::getRandomHash(), and RandomHash.
Member Function Documentation
iterator DatabaseManager::begin () inline
Definition at line 76 of file DatabaseManager.h.
const_iterator DatabaseManager::cbegin () const inline
Definition at line 78 of file DatabaseManager.h.
const_iterator DatabaseManager::cend () const inline
Definition at line 82 of file DatabaseManager.h.
iterator DatabaseManager::end () inline
Definition at line 80 of file DatabaseManager.h.
BBHash * DatabaseManager::getNearest (const BBHash & Hash) const
Returns the nearest BBHash from the given parameter in the database.
Definition at line 84 of file DatabaseManager.cpp.
References BBHash::distance(), BBHash::dotProduct(), Nearest, PrimeNumber, RandomHash, and w.
double DatabaseManager::getTime (const BBHash & Hash) const
Returns the execution time found in the database for the given Hash (BBDescritor).
Definition at line 70 of file DatabaseManager.cpp.
bool DatabaseManager::hasHash (const BBHash & Hash) const
Returns true if and only if there is an exactly equal hash on the database.
Definition at line 77 of file DatabaseManager.cpp.
void DatabaseManager::insert (BBHash Hash, double Value)
Insert a new value in the database.
Parameters
The first parameter is the hash and the second is the execution time of this hash.
Definition at line 111 of file DatabaseManager.cpp.
References BBHash::dotProduct(), PrimeNumber, RandomHash, Value, and w.
Referenced by main().
void DatabaseManager::printDatabase () const
Prints all the database. Each new line contains a hash and its execution time separated by space.
Definition at line 128 of file DatabaseManager.cpp.
Referenced by main().
int DatabaseManager::size () const
Returns the number of different BB hashes which there are in the database.
Definition at line 66 of file DatabaseManager.cpp.
void DatabaseManager::unionWith (DatabaseManager & DB2)
This function merge the database with the one given as parameter.
Definition at line 123 of file DatabaseManager.cpp.
The documentation for this class was generated from the following files:
DatabaseManager.h
DatabaseManager.cpp