GEOS - Guide for Exploration of the Optimization Space: ExecutionTimeMeasurer Class Reference
ExecutionTimeMeasurer Class Reference abstract
This class is a interface to implement a execution time measurer. The way that this execution is done can be implemented in diferents ways.
#include <ExecutionTimeMeasurer.h>
Public Member Functions
double getExecutionTime (std::vector< std::string > &Argv, char *const *Envp)
Call and measure the execution time of the run function passing the arguments argv and evnp to the module's main function.
double getExecutionTime ()
Call and measure the execution time of the run function.
~ExecutionTimeMeasurer ()
Detailed Description
This class is a interface to implement a execution time measurer. The way that this execution is done can be implemented in diferents ways.
Definition at line 35 of file ExecutionTimeMeasurer.h.
Constructor & Destructor Documentation
ExecutionTimeMeasurer::~ExecutionTimeMeasurer () inline
Definition at line 72 of file ExecutionTimeMeasurer.h.
Member Function Documentation
double ExecutionTimeMeasurer::getExecutionTime (std::vector< std::string > & Argv, char *const * Envp) inline
Call and measure the execution time of the run function passing the arguments argv and evnp to the module's main function.
Definition at line 56 of file ExecutionTimeMeasurer.h.
References getTimestamp().
Referenced by GEOS::getRealExecutionTime(), and GEOS::getRealExecutionTimeWithArgs().
double ExecutionTimeMeasurer::getExecutionTime () inline
Call and measure the execution time of the run function.
Definition at line 66 of file ExecutionTimeMeasurer.h.
The documentation for this class was generated from the following file:
ExecutionTimeMeasurer.h