GEOS - Guide to Exploration of Otimization's Sequences: BBHash Class Reference
BBHash Class Reference
This class is responsible for representing BB's hashes in memory. It can be constructed by a string (hash representation in the file) or by a basic block that will serve as a base to create a new hash.
#include <BBHash.h>
Public Member Functions
BBHash ()
Create an empty hash.
BBHash (llvm::BasicBlock &)
Create a hash for the Basic Block given as parameter.
BBHash (const llvm::StringRef &)
Creates a memory representation of the hash from a string representation of the hash. Useful when loading the hash from a file.
void setDescriptor (DescriptorKind, int)
set an information in the hash with a new value given as parameter.
void addUpDescriptor (DescriptorKind, int n=1)
Sum 1 or n to the value of an information in the hash.
int getDescriptor (DescriptorKind) const
get the value from an information in the hash.
llvm::StringRef getString () const
returns a string that represents this hash. For instance: "25-0-1-0-0-1-7-4-2-0-1-0-0-0-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1" Where each position represents the amount of something in the basic block. For example, in this case the first number is the number of instruction in the basic block. So this basic block had 25 instructions.
bool operator== (const BBHash &Other) const
Static Public Member Functions
static double distance (const BBHash &, const BBHash &)
Calculates an Euclidian distance between two hashes.
static int dotProduct (const BBHash &, const BBHash &)
Calculates the dot product between two hashes.
static BBHash * getRandomHash ()
Generates a randomic Hash.
Detailed Description
This class is responsible for representing BB's hashes in memory. It can be constructed by a string (hash representation in the file) or by a basic block that will serve as a base to create a new hash.
Definition at line 70 of file BBHash.h.
Constructor & Destructor Documentation
BBHash::BBHash ()
Create an empty hash.
Definition at line 137 of file BBHash.cpp.
BBHash::BBHash (llvm::BasicBlock &)
Create a hash for the Basic Block given as parameter.
BBHash::BBHash (const llvm::StringRef &)
Creates a memory representation of the hash from a string representation of the hash. Useful when loading the hash from a file.
Member Function Documentation
void BBHash::addUpDescriptor (DescriptorKind DescriptionId, int n = 1)
Sum 1 or n to the value of an information in the hash.
Definition at line 180 of file BBHash.cpp.
double BBHash::distance (const BBHash & a, const BBHash & b) static
Calculates an Euclidian distance between two hashes.
Returns
it returns a double that represents how equally two basic blocks are.
Definition at line 202 of file BBHash.cpp.
References getDescriptor().
Referenced by DatabaseManager::getNearest(), std::hash< BBHash >::operator()(), and operator==().
int BBHash::dotProduct (const BBHash & a, const BBHash & b) static
Calculates the dot product between two hashes.
Returns
it returns a double from the result of the dot product.
Definition at line 212 of file BBHash.cpp.
References getDescriptor().
Referenced by DatabaseManager::getNearest(), and DatabaseManager::insert().
int BBHash::getDescriptor (DescriptorKind DescriptionId) const
get the value from an information in the hash.
Definition at line 185 of file BBHash.cpp.
Referenced by distance(), dotProduct(), and std::hash< BBHash >::operator()().
BBHash * BBHash::getRandomHash () static
Generates a randomic Hash.
Definition at line 222 of file BBHash.cpp.
References RandomHash, and setDescriptor().
Referenced by DatabaseManager::DatabaseManager().
StringRef BBHash::getString () const
returns a string that represents this hash. For instance: "25-0-1-0-0-1-7-4-2-0-1-0-0-0-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1" Where each position represents the amount of something in the basic block. For example, in this case the first number is the number of instruction in the basic block. So this basic block had 25 instructions.
Definition at line 193 of file BBHash.cpp.
bool BBHash::operator== (const BBHash & Other) const inline
Definition at line 129 of file BBHash.h.
References distance().
void BBHash::setDescriptor (DescriptorKind DescriptionId, int Value)
set an information in the hash with a new value given as parameter.
Definition at line 171 of file BBHash.cpp.
References Value.
Referenced by getRandomHash().
The documentation for this class was generated from the following files:
BBHash.h
BBHash.cpp