GEOS - Guide to Exploration of Otimization's Sequences: mergeDatabase.cpp File Reference
mergeDatabase.cpp File Reference
This file contains the implementation of a basic block database. It's responsable for merging databases. Those databases constains hashs that represents each basic block and also their execution time.
#include "DatabaseManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
Functions
static cl::opt< std::string > DatabaseFilename ("database", cl::desc("Database filename to check for duplicates"), cl::value_desc("filename"), cl::Required)
cl::alias dbAlias ("db", cl::desc("Alias for -database"), cl::aliasopt(DatabaseFilename))
static cl::opt< std::string > HashFilename ("hash", cl::desc("Hash filename"), cl::value_desc("filename"), cl::Required)
cl::alias hsAlias ("hs", cl::desc("Alias for -hash"), cl::aliasopt(HashFilename))
static cl::opt< std::string > ProfFilename ("profile", cl::desc("Profile filename"), cl::value_desc("filename"), cl::Required)
cl::alias pAlias ("p", cl::desc("Alias for -profile"), cl::aliasopt(ProfFilename))
int main (int argc, char **argv)
Detailed Description
This file contains the implementation of a basic block database. It's responsable for merging databases. Those databases constains hashs that represents each basic block and also their execution time.
Definition in file mergeDatabase.cpp.
Function Documentation
static cl::opt<std::string> DatabaseFilename ("database" , cl:: desc"Database filename to check for duplicates", cl:: value_desc"filename", cl::Required) static
Referenced by main().
cl::alias dbAlias ("db" , cl:: desc"Alias for -database", cl:: aliasoptDatabaseFilename)
static cl::opt<std::string> HashFilename ("hash" , cl:: desc"Hash filename", cl:: value_desc"filename", cl::Required) static
Referenced by main().
cl::alias hsAlias ("hs" , cl:: desc"Alias for -hash", cl:: aliasoptHashFilename)
int main (int argc, char ** argv)
Definition at line 50 of file mergeDatabase.cpp.
References DatabaseFilename(), HashFilename(), DatabaseManager::printDatabase(), ProfFilename(), and DatabaseManager::unionWith().
cl::alias pAlias ("p" , cl:: desc"Alias for -profile", cl:: aliasoptProfFilename)
static cl::opt<std::string> ProfFilename ("profile" , cl:: desc"Profile filename", cl:: value_desc"filename", cl::Required) static
Referenced by main().