GEOS - Guide to Exploration of Otimization's Sequences: GEOS Namespace Reference
GEOS Namespace Reference
This namespace is responsable for applying passes into a ProfileModule, which contains the LLVM code and the profiling information, and also analyse its execution time.
Functions
AnalysisMethod * getAnalyser (AnalysisMethodKind, llvm::StringRef)
Instantiates the specificated AnlysisMethod.
llvm::Pass * getPass (OptimizationKind)
Returns the instanciation of the optimization choosed.
ProfileModule * applyPassesOnFunction (llvm::StringRef, const ProfileModule &, llvm::FunctionPassManager &)
Like applyPasses this function apply a set of passes to the llvm module. However, it just apply those to an specific function.
ProfileModule * applyPasses (const ProfileModule &, llvm::FunctionPassManager &)
Apply Passes (Transformations) into a ProfileModule. Also ensures that its profiling information ramains consistent. The ProfileModule given as parameter isn't modified, actualy all the modifications are made in a copy. This copy is returned as parameter.
double analyseFunctionExecutionTime (llvm::StringRef, const ProfileModule &, AnalysisMethod *)
Estimate the execution time of a function from the ProfileModule with the given AnalysisMethod and returns it.
double analyseExecutionTime (const ProfileModule &, AnalysisMethod *)
Estimate the execution time of a ProfileModule with the given AnalysisMethod and returns it.
Detailed Description
This namespace is responsable for applying passes into a ProfileModule, which contains the LLVM code and the profiling information, and also analyse its execution time.
Function Documentation
double GEOS::analyseExecutionTime (const ProfileModule & PModule, AnalysisMethod * Analyser)
Estimate the execution time of a ProfileModule with the given AnalysisMethod and returns it.
Definition at line 214 of file GEOS.cpp.
References AnalysisMethod::estimateExecutionTime(), and ProfileModule::getLLVMModule().
Referenced by main().
double GEOS::analyseFunctionExecutionTime (llvm::StringRef , const ProfileModule & , AnalysisMethod *)
Estimate the execution time of a function from the ProfileModule with the given AnalysisMethod and returns it.
Parameters
The first param is the name of the function that the analysis should be done.
ProfileModule* GEOS::applyPasses (const ProfileModule & , llvm::FunctionPassManager &)
Apply Passes (Transformations) into a ProfileModule. Also ensures that its profiling information ramains consistent. The ProfileModule given as parameter isn't modified, actualy all the modifications are made in a copy. This copy is returned as parameter.
Referenced by main().
ProfileModule* GEOS::applyPassesOnFunction (llvm::StringRef , const ProfileModule & , llvm::FunctionPassManager &)
Like applyPasses this function apply a set of passes to the llvm module. However, it just apply those to an specific function.
Parameters
the first param is the function name that the passes should be applied.
Referenced by main().
AnalysisMethod* GEOS::getAnalyser (AnalysisMethodKind , llvm::StringRef)
Instantiates the specificated AnlysisMethod.
Parameters
First is the AnalysisMethod kind and the second is the database file path.
Referenced by main().
Pass * GEOS::getPass (OptimizationKind OptChoosed)
Returns the instanciation of the optimization choosed.
Definition at line 64 of file GEOS.cpp.
References AddDiscriminators, AggressiveDCE, AlignmentFromAssumptions, BreakCriticalEdges, CFGSimplification, CFGStructurization, ConstantHoisting, ConstantPropagation, DeadCodeElimination, DeadInstElimination, DemoteRegisterToMemory, EarlyCSE, FlattenCFG, GVN, InductionVariableSimplify, InstructionCombining, InstructionNamer, InstructionSimplifier, JumpThreading, LCSSA, LICM, LoopDeletion, LoopIdiom, LoopReroll, LoopRotate, LoopSimplify, LoopStrengthReduce, LoopUnroll, LoopUnswitch, LowerAtomic, LowerSwitch, MemCpyOpt, MergedLoadStoreMotion, PromoteMemoryToRegister, Reassociate, ScalarizerPass, ScalarReplAggregates, SeparateConstOffsetFromGEP, Sink, SROA, TailCallElimination, and ValuePropagation.
Referenced by main().