GEOS - Guide for Exploration of the Optimization Space: PAPI.cpp File Reference
PAPI.cpp File Reference
This file contains the implementation of a set of functions used to mensure the execution time of blocks of codes. Calls for this functions can be inserted in a code two get information of its execution.
#include <stdio.h>
#include <cstdlib>
#include "../../../../include/Profiling/papi.h"
#include <cmath>
Macros
#define TIME 100
Functions
long long int getEmpty (int *Events, long long int *Values)
void init_PAPI (int Size)
double get_time_stamp ()
void start_measures (int Id)
void get_results ()
void print_results ()
Variables
int ID
int * Freq
double * Value
int SIZE
Detailed Description
This file contains the implementation of a set of functions used to mensure the execution time of blocks of codes. Calls for this functions can be inserted in a code two get information of its execution.
Definition in file PAPI.cpp.
Macro Definition Documentation
#define TIME 100
Definition at line 23 of file PAPI.cpp.
Referenced by get_results(), and start_measures().
Function Documentation
void get_results ()
Definition at line 70 of file PAPI.cpp.
References Freq, get_time_stamp(), ID, TIME, and Value.
double get_time_stamp ()
Definition at line 53 of file PAPI.cpp.
References Empty, Events, getEmpty(), PAPI_stop_counters(), and Values.
Referenced by get_results().
long long int getEmpty (int * Events, long long int * Values)
Definition at line 30 of file PAPI.cpp.
References PAPI_start_counters(), and PAPI_stop_counters().
Referenced by get_time_stamp(), init_PAPI(), and start_measures().
void init_PAPI (int Size)
Definition at line 37 of file PAPI.cpp.
References Events, Freq, getEmpty(), PAPI_library_init(), PAPI_VER_CURRENT, SIZE, Value, and Values.
void print_results ()
Definition at line 75 of file PAPI.cpp.
References Freq, SIZE, and Value.
void start_measures (int Id)
Definition at line 61 of file PAPI.cpp.
References Empty, Events, Freq, getEmpty(), ID, PAPI_start_counters(), TIME, and Values.
Variable Documentation
int* Freq
Definition at line 26 of file PAPI.cpp.
Referenced by get_results(), init_PAPI(), print_results(), ProfileModule::setBasicBlockFrequency(), and start_measures().
int ID
Definition at line 25 of file PAPI.cpp.
Referenced by get_results(), and start_measures().
int SIZE
Definition at line 28 of file PAPI.cpp.
Referenced by init_PAPI(), and print_results().
double* Value
Definition at line 27 of file PAPI.cpp.
Referenced by get_results(), getShuffleAndOtherOprd(), init_PAPI(), matchPairwiseReductionAtLevel(), matchVectorSplittingReduction(), and print_results().