GEOS - Guide for Exploration of the Optimization Space: papi.h File Reference
papi.h File Reference
#include <sys/types.h>
#include <limits.h>
#include "papiStdEventDefs.h"
#include <signal.h>
Classes
struct _papi_sprofil
struct _papi_overflow_option
struct _papi_inherit_option
struct _papi_domain_option
struct _papi_granularity_option
struct _papi_preload_option
struct _papi_substrate_option
struct _papi_debug_option
struct _papi_address_map
struct _papi_program_info
struct _papi_shared_lib_info
struct _papi_mh_tlb_info
struct _papi_mh_cache_info
struct _papi_mh_level_info
struct _papi_mh_info
struct _papi_hw_info
struct _papi_multiplex_option
union PAPI_option_t
struct event_info
Macros
#define PAPI_VERSION_NUMBER(maj, min, rev) (((maj)<<16) | ((min)<<8) | (rev))
#define PAPI_VERSION_MAJOR(x) (((x)>>16) & 0xffff)
#define PAPI_VERSION_MINOR(x) (((x)>>8) & 0xff)
#define PAPI_VERSION_REVISION(x) ((x) & 0xff)
#define PAPI_VERSION PAPI_VERSION_NUMBER(3,0,7)
#define PAPI_VER_CURRENT (PAPI_VERSION & 0xffffff00)
#define PAPI_OK 0 /*No error */
#define PAPI_EINVAL -1 /*Invalid argument */
#define PAPI_ENOMEM -2 /*Insufficient memory */
#define PAPI_ESYS -3 /*A System/C library call failed, please check errno */
#define PAPI_ESBSTR
#define PAPI_ECLOST -5 /*Access to the counters was lost or interrupted */
#define PAPI_EBUG -6 /*Internal error, please send mail to the developers */
#define PAPI_ENOEVNT -7 /*Hardware Event does not exist */
#define PAPI_ECNFLCT
#define PAPI_ENOTRUN -9 /*No Events or EventSets are currently counting */
#define PAPI_EISRUN -10 /*Events or EventSets are currently counting */
#define PAPI_ENOEVST -11 /* No EventSet Available */
#define PAPI_ENOTPRESET -12 /* Not a Preset Event in argument */
#define PAPI_ENOCNTR -13 /* Hardware does not support counters */
#define PAPI_EMISC -14 /* No clue as to what this error code means */
#define PAPI_EPERM -15 /* You lack the necessary permissions */
#define PAPI_NOT_INITED 0
#define PAPI_LOW_LEVEL_INITED 1 /* Low level has called library init */
#define PAPI_HIGH_LEVEL_INITED 2 /* High level has called library init */
#define PAPI_THREAD_LEVEL_INITED 4 /* Threads have been inited */
#define PAPI_NULL -1 /*A nonexistent hardware event used as a placeholder */
#define PAPI_DOM_USER 0x1 /* User context counted */
#define PAPI_DOM_MIN PAPI_DOM_USER
#define PAPI_DOM_KERNEL 0x2 /* Kernel/OS context counted */
#define PAPI_DOM_OTHER 0x4 /* Exception/transient mode (like user TLB misses) */
#define PAPI_DOM_ALL (PAPI_DOM_USER|PAPI_DOM_KERNEL|PAPI_DOM_OTHER) /* All contexts counted */
#define PAPI_DOM_MAX PAPI_DOM_ALL
#define PAPI_DOM_HWSPEC
#define PAPI_USR1_TLS 0
#define PAPI_USR2_TLS 1
#define PAPI_HIGH_LEVEL_TLS 2
#define PAPI_NUM_TLS 3
#define PAPI_USR1_LOCK 0 /* User controlled locks */
#define PAPI_USR2_LOCK 1 /* User controlled locks */
#define PAPI_NUM_LOCK 2 /* Used with setting up array */
#define PAPI_VENDOR_UNKNOWN -1
#define PAPI_VENDOR_INTEL 1
#define PAPI_VENDOR_AMD 2
#define PAPI_VENDOR_CYRIX 3
#define PAPI_GRN_THR 0x1 /* PAPI counters for each individual thread */
#define PAPI_GRN_MIN PAPI_GRN_THR
#define PAPI_GRN_PROC 0x2 /* PAPI counters for each individual process */
#define PAPI_GRN_PROCG 0x4 /* PAPI counters for each individual process group */
#define PAPI_GRN_SYS 0x8 /* PAPI counters for the current CPU, are you bound? */
#define PAPI_GRN_SYS_CPU 0x10 /* PAPI counters for all CPU's individually */
#define PAPI_GRN_MAX PAPI_GRN_SYS_CPU
#define PAPI_MPX_DEF_US 10000 /*Default resolution in us. of mpx handler */
#define PAPI_MPX_DEF_DEG 32 /* Maximum number of counters we can mpx */
#define PAPI_STOPPED 0x01 /* EventSet stopped */
#define PAPI_RUNNING 0x02 /* EventSet running */
#define PAPI_PAUSED 0x04 /* EventSet temp. disabled by the library */
#define PAPI_NOT_INIT 0x08 /* EventSet defined, but not initialized */
#define PAPI_OVERFLOWING 0x10 /* EventSet has overflowing enabled */
#define PAPI_PROFILING 0x20 /* EventSet has profiling enabled */
#define PAPI_MULTIPLEXING 0x40 /* EventSet has multiplexing enabled */
#define PAPI_NUM_ERRORS 16 /* Number of error messages specified in this API. */
#define PAPI_QUIET 0 /* Option to turn off automatic reporting of return codes < 0 to stderr. */
#define PAPI_VERB_ECONT 1 /* Option to automatically report any return codes < 0 to stderr and continue. */
#define PAPI_VERB_ESTOP 2 /* Option to automatically report any return codes < 0 to stderr and exit. */
#define PAPI_GET_SIZE 1 /* Size of process image in pages */
#define PAPI_GET_RESSIZE 2 /* Resident set size in pages */
#define PAPI_GET_PAGESIZE 3 /* Pagesize in bytes */
#define PAPI_PROFIL_POSIX 0x0 /* Default type of profiling, similar to 'man profil'. */
#define PAPI_PROFIL_RANDOM 0x1 /* Drop a random 25% of the samples. */
#define PAPI_PROFIL_WEIGHTED 0x2 /* Weight the samples by their value. */
#define PAPI_PROFIL_COMPRESS 0x4 /* Ignore samples if hash buckets get big. */
#define PAPI_PROFIL_BUCKET_16 0x8 /* Use 16 bit buckets to accumulate profile info (default) */
#define PAPI_PROFIL_BUCKET_32 0x10 /* Use 32 bit buckets to accumulate profile info */
#define PAPI_PROFIL_BUCKET_64 0x20 /* Use 64 bit buckets to accumulate profile info */
#define PAPI_PROFIL_FORCE_SW 0x40 /* Force Software overflow in profiling */
#define PAPI_PROFIL_BUCKETS (PAPI_PROFIL_BUCKET_16 | PAPI_PROFIL_BUCKET_32 | PAPI_PROFIL_BUCKET_64)
#define PAPI_OVERFLOW_FORCE_SW 0x40 /* Force using Software */
#define PAPI_OVERFLOW_HARDWARE 0x80 /* Using Hardware */
#define PAPI_INHERIT_ALL 1 /* The flag to this to inherit all children's counters */
#define PAPI_INHERIT_NONE 0 /* The flag to this to inherit none of the children's counters */
#define PAPI_DEBUG 2 /* Option to turn on debugging features of the PAPI library */
#define PAPI_MULTIPLEX 3 /* Turn on/off or multiplexing for an eventset */
#define PAPI_DEFDOM 4 /* Domain for all new eventsets. Takes non-NULL option pointer. */
#define PAPI_DOMAIN 5 /* Domain for an eventset */
#define PAPI_DEFGRN 6 /* Granularity for all new eventsets */
#define PAPI_GRANUL 7 /* Granularity for an eventset */
#define PAPI_INHERIT 8 /* Child threads/processes inherit counter config and progate values up upon exit. */
#define PAPI_CPUS 9 /* Return the maximum number of CPU's usable/detected */
#define PAPI_THREADS 10 /* Return the number of threads usable/detected by PAPI */
#define PAPI_NUMCTRS 11 /* The number of counters returned by reading this eventset */
#define PAPI_PROFIL 12 /* Option to turn on the overflow/profil reporting software */
#define PAPI_PRELOAD 13 /* Option to find out the environment variable that can preload libraries */
#define PAPI_CLOCKRATE 14 /* Clock rate in MHz */
#define PAPI_MAX_HWCTRS 15 /* Number of physical hardware counters */
#define PAPI_HWINFO 16 /* Hardware information */
#define PAPI_EXEINFO 17 /* Executable information */
#define PAPI_MAX_CPUS 18 /* Number of ncpus we can talk to from here */
#define PAPI_SHLIBINFO 20 /* Shared Library information */
#define PAPI_LIB_VERSION 21 /* Option to find out the complete version number of the PAPI library */
#define PAPI_SUBSTRATE_SUPPORT 22 /* Find out what the substrate supports */
#define PAPI_INIT_SLOTS
#define PAPI_MIN_STR_LEN 40 /* For small strings, like names & stuff */
#define PAPI_MAX_STR_LEN 129 /* For average run-of-the-mill strings */
#define PAPI_HUGE_STR_LEN 1024 /* This should be defined in terms of a system parameter */
#define PAPI_DERIVED 0x1 /* Flag to indicate that the event is derived */
#define long_long long long
#define u_long_long unsigned long long
#define papi_i64 long_long
#define papi_i32 int
#define papi_i16 short
#define papi_ui64 u_long_long
#define papi_ui32 unsigned int
#define papi_ui16 unsigned short
#define PAPI_MAX_MEM_HIERARCHY_LEVELS 3
#define PAPI_MH_TYPE_EMPTY 0x0
#define PAPI_MH_TYPE_INST 0x1
#define PAPI_MH_TYPE_DATA 0x2
#define PAPI_MH_TYPE_VECTOR 0x4
#define PAPI_MH_TYPE_UNIFIED (PAPI_MH_TYPE_INST|PAPI_MH_TYPE_DATA)
#define PAPI_MH_CACHE_TYPE(a) (a & 0xf)
#define PAPI_MH_TYPE_WT 0x00 /* write-through cache */
#define PAPI_MH_TYPE_WB 0x10 /* write-back cache */
#define PAPI_MH_CACHE_WRITE_POLICY(a) (a & 0xf0)
#define PAPI_MH_TYPE_UNKNOWN 0x000
#define PAPI_MH_TYPE_LRU 0x100
#define PAPI_MH_TYPE_PSEUDO_LRU 0x200
#define PAPI_MH_CACHE_REPLACEMENT_POLICY(a) (a & 0xf00)
#define PAPI_MAX_INFO_TERMS 8
Typedefs
typedef void(* PAPI_overflow_handler_t)(int EventSet, void *address, long_long overflow_vector, void *context)
typedef struct _papi_sprofil PAPI_sprofil_t
typedef struct
_papi_overflow_option PAPI_overflow_option_t
typedef struct _papi_inherit_option PAPI_inherit_option_t
typedef struct _papi_domain_option PAPI_domain_option_t
typedef struct
_papi_granularity_option PAPI_granularity_option_t
typedef struct _papi_preload_option PAPI_preload_info_t
typedef struct
_papi_substrate_option PAPI_substrate_info_t
typedef int(* PAPI_debug_handler_t)(int code)
typedef struct _papi_debug_option PAPI_debug_option_t
typedef struct _papi_address_map PAPI_address_map_t
typedef struct _papi_program_info PAPI_exe_info_t
typedef struct
_papi_shared_lib_info PAPI_shlib_info_t
typedef struct _papi_mh_tlb_info PAPI_mh_tlb_info_t
typedef struct _papi_mh_cache_info PAPI_mh_cache_info_t
typedef struct _papi_mh_level_info PAPI_mh_level_t
typedef struct _papi_mh_info PAPI_mh_info_t
typedef struct _papi_hw_info PAPI_hw_info_t
typedef struct
_papi_multiplex_option PAPI_multiplex_option_t
typedef struct event_info PAPI_event_info_t
Enumerations
enum {
PAPI_ENUM_ALL = 0, PAPI_PRESET_ENUM_AVAIL, PAPI_PRESET_ENUM_INS, PAPI_PRESET_ENUM_BR,
PAPI_PRESET_ENUM_MEM, PAPI_PRESET_ENUM_TLB, PAPI_PRESET_ENUM_FP, PAPI_PENT4_ENUM_GROUPS = 0x100,
PAPI_PENT4_ENUM_COMBOS, PAPI_PENT4_ENUM_BITS, PAPI_PWR4_ENUM_GROUPS = 0x200
}
Functions
long long int getEmpty (int *, long long int *)
void init_PAPI (int)
void start_measures (int)
void get_results ()
void print_results ()
int PAPI_accum (int EventSet, long_long *values)
int PAPI_add_event (int EventSet, int Event)
int PAPI_add_events (int EventSet, int *Events, int number)
int PAPI_cleanup_eventset (int EventSet)
int PAPI_create_eventset (int *EventSet)
int PAPI_destroy_eventset (int *EventSet)
int PAPI_enum_event (int *EventCode, int modifier)
int PAPI_event_code_to_name (int EventCode, char *out)
int PAPI_event_name_to_code (char *in, int *out)
int PAPI_get_event_info (int EventCode, PAPI_event_info_t *info)
const PAPI_exe_info_t * PAPI_get_executable_info (void)
const PAPI_hw_info_t * PAPI_get_hardware_info (void)
int PAPI_get_multiplex (int EventSet)
int PAPI_get_opt (int option, PAPI_option_t *ptr)
long_long PAPI_get_real_cyc (void)
long_long PAPI_get_real_usec (void)
const PAPI_shlib_info_t * PAPI_get_shared_lib_info (void)
int PAPI_get_thr_specific (int tag, void **ptr)
int PAPI_get_overflow_event_index (int Eventset, long_long overflow_vector, int *array, int *number)
long_long PAPI_get_virt_cyc (void)
long_long PAPI_get_virt_usec (void)
int PAPI_is_initialized (void)
int PAPI_library_init (int version)
int PAPI_list_events (int EventSet, int *Events, int *number)
int PAPI_lock (int)
int PAPI_multiplex_init (void)
int PAPI_num_hwctrs (void)
int PAPI_num_events (int EventSet)
int PAPI_overflow (int EventSet, int EventCode, int threshold, int flags, PAPI_overflow_handler_t handler)
int PAPI_perror (int code, char *destination, int length)
int PAPI_profil (void *buf, unsigned bufsiz, caddr_t offset, unsigned scale, int EventSet, int EventCode, int threshold, int flags)
int PAPI_query_event (int EventCode)
int PAPI_read (int EventSet, long_long *values)
int PAPI_register_thread (void)
int PAPI_remove_event (int EventSet, int EventCode)
int PAPI_remove_events (int EventSet, int *Events, int number)
int PAPI_reset (int EventSet)
int PAPI_set_debug (int level)
int PAPI_set_domain (int domain)
int PAPI_set_granularity (int granularity)
int PAPI_set_multiplex (int EventSet)
int PAPI_set_opt (int option, PAPI_option_t *ptr)
int PAPI_set_thr_specific (int tag, void *ptr)
void PAPI_shutdown (void)
int PAPI_sprofil (PAPI_sprofil_t *prof, int profcnt, int EventSet, int EventCode, int threshold, int flags)
int PAPI_start (int EventSet)
int PAPI_state (int EventSet, int *status)
int PAPI_stop (int EventSet, long_long *values)
char * PAPI_strerror (int)
unsigned long PAPI_thread_id (void)
int PAPI_thread_init (unsigned long int(*id_fn)(void))
int PAPI_unlock (int)
int PAPI_unregister_thread (void)
int PAPI_write (int EventSet, long_long *values)
int PAPI_accum_counters (long_long *values, int array_len)
int PAPI_num_counters (void)
int PAPI_read_counters (long_long *values, int array_len)
int PAPI_start_counters (int *events, int array_len)
int PAPI_stop_counters (long_long *values, int array_len)
int PAPI_flips (float *rtime, float *ptime, long_long *flpins, float *mflips)
int PAPI_flops (float *rtime, float *ptime, long_long *flpops, float *mflops)
int PAPI_ipc (float *rtime, float *ptime, long_long *ins, float *ipc)
Variables
int Events [2]
long long int Values [2]
long long int Empty
Macro Definition Documentation
#define long_long long long
Definition at line 294 of file papi.h.
#define PAPI_CLOCKRATE 14 /* Clock rate in MHz */
Definition at line 222 of file papi.h.
#define PAPI_CPUS 9 /* Return the maximum number of CPU's usable/detected */
Definition at line 217 of file papi.h.
#define PAPI_DEBUG 2 /* Option to turn on debugging features of the PAPI library */
Definition at line 208 of file papi.h.
#define PAPI_DEFDOM 4 /* Domain for all new eventsets. Takes non-NULL option pointer. */
Definition at line 210 of file papi.h.
#define PAPI_DEFGRN 6 /* Granularity for all new eventsets */
Definition at line 213 of file papi.h.
#define PAPI_DERIVED 0x1 /* Flag to indicate that the event is derived */
Definition at line 238 of file papi.h.
#define PAPI_DOM_ALL (PAPI_DOM_USER|PAPI_DOM_KERNEL|PAPI_DOM_OTHER) /* All contexts counted */
Definition at line 102 of file papi.h.
#define PAPI_DOM_HWSPEC
Value:
0x80000000     /* Flag that indicates we are not reading CPU like stuff.
                                           The lower 31 bits can be decoded by the substrate into something
                                           meaningful. i.e. SGI HUB counters */
Definition at line 105 of file papi.h.
#define PAPI_DOM_KERNEL 0x2 /* Kernel/OS context counted */
Definition at line 100 of file papi.h.
#define PAPI_DOM_MAX PAPI_DOM_ALL
Definition at line 104 of file papi.h.
#define PAPI_DOM_MIN PAPI_DOM_USER
Definition at line 99 of file papi.h.
#define PAPI_DOM_OTHER 0x4 /* Exception/transient mode (like user TLB misses) */
Definition at line 101 of file papi.h.
#define PAPI_DOM_USER 0x1 /* User context counted */
Definition at line 98 of file papi.h.
#define PAPI_DOMAIN 5 /* Domain for an eventset */
Definition at line 212 of file papi.h.
#define PAPI_EBUG -6 /*Internal error, please send mail to the developers */
Definition at line 71 of file papi.h.
#define PAPI_ECLOST -5 /*Access to the counters was lost or interrupted */
Definition at line 70 of file papi.h.
#define PAPI_ECNFLCT
Value:
-8        /*Hardware Event exists, but cannot be counted
                                   due to counter resource limitations */
Definition at line 73 of file papi.h.
#define PAPI_EINVAL -1 /*Invalid argument */
Definition at line 65 of file papi.h.
#define PAPI_EISRUN -10 /*Events or EventSets are currently counting */
Definition at line 76 of file papi.h.
#define PAPI_EMISC -14 /* No clue as to what this error code means */
Definition at line 80 of file papi.h.
#define PAPI_ENOCNTR -13 /* Hardware does not support counters */
Definition at line 79 of file papi.h.
#define PAPI_ENOEVNT -7 /*Hardware Event does not exist */
Definition at line 72 of file papi.h.
#define PAPI_ENOEVST -11 /* No EventSet Available */
Definition at line 77 of file papi.h.
#define PAPI_ENOMEM -2 /*Insufficient memory */
Definition at line 66 of file papi.h.
#define PAPI_ENOTPRESET -12 /* Not a Preset Event in argument */
Definition at line 78 of file papi.h.
#define PAPI_ENOTRUN -9 /*No Events or EventSets are currently counting */
Definition at line 75 of file papi.h.
#define PAPI_EPERM -15 /* You lack the necessary permissions */
Definition at line 81 of file papi.h.
#define PAPI_ESBSTR
Value:
-4        /*Substrate returned an error,
                                   usually the result of an unimplemented feature */
Definition at line 68 of file papi.h.
#define PAPI_ESYS -3 /*A System/C library call failed, please check errno */
Definition at line 67 of file papi.h.
#define PAPI_EXEINFO 17 /* Executable information */
Definition at line 225 of file papi.h.
#define PAPI_GET_PAGESIZE 3 /* Pagesize in bytes */
Definition at line 186 of file papi.h.
#define PAPI_GET_RESSIZE 2 /* Resident set size in pages */
Definition at line 185 of file papi.h.
#define PAPI_GET_SIZE 1 /* Size of process image in pages */
Definition at line 184 of file papi.h.
#define PAPI_GRANUL 7 /* Granularity for an eventset */
Definition at line 214 of file papi.h.
#define PAPI_GRN_MAX PAPI_GRN_SYS_CPU
Definition at line 144 of file papi.h.
#define PAPI_GRN_MIN PAPI_GRN_THR
Definition at line 139 of file papi.h.
#define PAPI_GRN_PROC 0x2 /* PAPI counters for each individual process */
Definition at line 140 of file papi.h.
#define PAPI_GRN_PROCG 0x4 /* PAPI counters for each individual process group */
Definition at line 141 of file papi.h.
#define PAPI_GRN_SYS 0x8 /* PAPI counters for the current CPU, are you bound? */
Definition at line 142 of file papi.h.
#define PAPI_GRN_SYS_CPU 0x10 /* PAPI counters for all CPU's individually */
Definition at line 143 of file papi.h.
#define PAPI_GRN_THR 0x1 /* PAPI counters for each individual thread */
Definition at line 138 of file papi.h.
#define PAPI_HIGH_LEVEL_INITED 2 /* High level has called library init */
Definition at line 85 of file papi.h.
#define PAPI_HIGH_LEVEL_TLS 2
Definition at line 117 of file papi.h.
#define PAPI_HUGE_STR_LEN 1024 /* This should be defined in terms of a system parameter */
Definition at line 236 of file papi.h.
#define PAPI_HWINFO 16 /* Hardware information */
Definition at line 224 of file papi.h.
#define papi_i16 short
Definition at line 307 of file papi.h.
#define papi_i32 int
Definition at line 306 of file papi.h.
#define papi_i64 long_long
Definition at line 305 of file papi.h.
#define PAPI_INHERIT 8 /* Child threads/processes inherit counter config and progate values up upon exit. */
Definition at line 215 of file papi.h.
#define PAPI_INHERIT_ALL 1 /* The flag to this to inherit all children's counters */
Definition at line 205 of file papi.h.
#define PAPI_INHERIT_NONE 0 /* The flag to this to inherit none of the children's counters */
Definition at line 206 of file papi.h.
#define PAPI_INIT_SLOTS
Value:
64     /*Number of initialized slots in
                                   DynamicArray of EventSets */
Definition at line 231 of file papi.h.
#define PAPI_LIB_VERSION 21 /* Option to find out the complete version number of the PAPI library */
Definition at line 228 of file papi.h.
#define PAPI_LOW_LEVEL_INITED 1 /* Low level has called library init */
Definition at line 84 of file papi.h.
#define PAPI_MAX_CPUS 18 /* Number of ncpus we can talk to from here */
Definition at line 226 of file papi.h.
#define PAPI_MAX_HWCTRS 15 /* Number of physical hardware counters */
Definition at line 223 of file papi.h.
#define PAPI_MAX_INFO_TERMS 8
Definition at line 504 of file papi.h.
#define PAPI_MAX_MEM_HIERARCHY_LEVELS 3
Definition at line 397 of file papi.h.
#define PAPI_MAX_STR_LEN 129 /* For average run-of-the-mill strings */
Definition at line 235 of file papi.h.
#define PAPI_MH_CACHE_REPLACEMENT_POLICY (a) (a & 0xf00)
Definition at line 410 of file papi.h.
#define PAPI_MH_CACHE_TYPE (a) (a & 0xf)
Definition at line 403 of file papi.h.
#define PAPI_MH_CACHE_WRITE_POLICY (a) (a & 0xf0)
Definition at line 406 of file papi.h.
#define PAPI_MH_TYPE_DATA 0x2
Definition at line 400 of file papi.h.
#define PAPI_MH_TYPE_EMPTY 0x0
Definition at line 398 of file papi.h.
#define PAPI_MH_TYPE_INST 0x1
Definition at line 399 of file papi.h.
#define PAPI_MH_TYPE_LRU 0x100
Definition at line 408 of file papi.h.
#define PAPI_MH_TYPE_PSEUDO_LRU 0x200
Definition at line 409 of file papi.h.
#define PAPI_MH_TYPE_UNIFIED (PAPI_MH_TYPE_INST|PAPI_MH_TYPE_DATA)
Definition at line 402 of file papi.h.
#define PAPI_MH_TYPE_UNKNOWN 0x000
Definition at line 407 of file papi.h.
#define PAPI_MH_TYPE_VECTOR 0x4
Definition at line 401 of file papi.h.
#define PAPI_MH_TYPE_WB 0x10 /* write-back cache */
Definition at line 405 of file papi.h.
#define PAPI_MH_TYPE_WT 0x00 /* write-through cache */
Definition at line 404 of file papi.h.
#define PAPI_MIN_STR_LEN 40 /* For small strings, like names & stuff */
Definition at line 234 of file papi.h.
#define PAPI_MPX_DEF_DEG 32 /* Maximum number of counters we can mpx */
Definition at line 164 of file papi.h.
#define PAPI_MPX_DEF_US 10000 /*Default resolution in us. of mpx handler */
Definition at line 163 of file papi.h.
#define PAPI_MULTIPLEX 3 /* Turn on/off or multiplexing for an eventset */
Definition at line 209 of file papi.h.
#define PAPI_MULTIPLEXING 0x40 /* EventSet has multiplexing enabled */
Definition at line 174 of file papi.h.
#define PAPI_NOT_INIT 0x08 /* EventSet defined, but not initialized */
Definition at line 171 of file papi.h.
#define PAPI_NOT_INITED 0
Definition at line 83 of file papi.h.
#define PAPI_NULL -1 /*A nonexistent hardware event used as a placeholder */
Definition at line 94 of file papi.h.
#define PAPI_NUM_ERRORS 16 /* Number of error messages specified in this API. */
Definition at line 178 of file papi.h.
#define PAPI_NUM_LOCK 2 /* Used with setting up array */
Definition at line 127 of file papi.h.
#define PAPI_NUM_TLS 3
Definition at line 118 of file papi.h.
#define PAPI_NUMCTRS 11 /* The number of counters returned by reading this eventset */
Definition at line 219 of file papi.h.
#define PAPI_OK 0 /*No error */
Definition at line 64 of file papi.h.
#define PAPI_OVERFLOW_FORCE_SW 0x40 /* Force using Software */
Definition at line 200 of file papi.h.
#define PAPI_OVERFLOW_HARDWARE 0x80 /* Using Hardware */
Definition at line 201 of file papi.h.
#define PAPI_OVERFLOWING 0x10 /* EventSet has overflowing enabled */
Definition at line 172 of file papi.h.
#define PAPI_PAUSED 0x04 /* EventSet temp. disabled by the library */
Definition at line 170 of file papi.h.
#define PAPI_PRELOAD 13 /* Option to find out the environment variable that can preload libraries */
Definition at line 221 of file papi.h.
#define PAPI_PROFIL 12 /* Option to turn on the overflow/profil reporting software */
Definition at line 220 of file papi.h.
#define PAPI_PROFIL_BUCKET_16 0x8 /* Use 16 bit buckets to accumulate profile info (default) */
Definition at line 193 of file papi.h.
#define PAPI_PROFIL_BUCKET_32 0x10 /* Use 32 bit buckets to accumulate profile info */
Definition at line 194 of file papi.h.
#define PAPI_PROFIL_BUCKET_64 0x20 /* Use 64 bit buckets to accumulate profile info */
Definition at line 195 of file papi.h.
#define PAPI_PROFIL_BUCKETS (PAPI_PROFIL_BUCKET_16 | PAPI_PROFIL_BUCKET_32 | PAPI_PROFIL_BUCKET_64)
Definition at line 197 of file papi.h.
#define PAPI_PROFIL_COMPRESS 0x4 /* Ignore samples if hash buckets get big. */
Definition at line 192 of file papi.h.
#define PAPI_PROFIL_FORCE_SW 0x40 /* Force Software overflow in profiling */
Definition at line 196 of file papi.h.
#define PAPI_PROFIL_POSIX 0x0 /* Default type of profiling, similar to 'man profil'. */
Definition at line 189 of file papi.h.
#define PAPI_PROFIL_RANDOM 0x1 /* Drop a random 25% of the samples. */
Definition at line 190 of file papi.h.
#define PAPI_PROFIL_WEIGHTED 0x2 /* Weight the samples by their value. */
Definition at line 191 of file papi.h.
#define PAPI_PROFILING 0x20 /* EventSet has profiling enabled */
Definition at line 173 of file papi.h.
#define PAPI_QUIET 0 /* Option to turn off automatic reporting of return codes < 0 to stderr. */
Definition at line 179 of file papi.h.
#define PAPI_RUNNING 0x02 /* EventSet running */
Definition at line 169 of file papi.h.
#define PAPI_SHLIBINFO 20 /* Shared Library information */
Definition at line 227 of file papi.h.
#define PAPI_STOPPED 0x01 /* EventSet stopped */
Definition at line 168 of file papi.h.
#define PAPI_SUBSTRATE_SUPPORT 22 /* Find out what the substrate supports */
Definition at line 229 of file papi.h.
#define PAPI_THREAD_LEVEL_INITED 4 /* Threads have been inited */
Definition at line 86 of file papi.h.
#define PAPI_THREADS 10 /* Return the number of threads usable/detected by PAPI */
Definition at line 218 of file papi.h.
#define papi_ui16 unsigned short
Definition at line 310 of file papi.h.
#define papi_ui32 unsigned int
Definition at line 309 of file papi.h.
#define papi_ui64 u_long_long
Definition at line 308 of file papi.h.
#define PAPI_USR1_LOCK 0 /* User controlled locks */
Definition at line 125 of file papi.h.
#define PAPI_USR1_TLS 0
Definition at line 115 of file papi.h.
#define PAPI_USR2_LOCK 1 /* User controlled locks */
Definition at line 126 of file papi.h.
#define PAPI_USR2_TLS 1
Definition at line 116 of file papi.h.
#define PAPI_VENDOR_AMD 2
Definition at line 133 of file papi.h.
#define PAPI_VENDOR_CYRIX 3
Definition at line 134 of file papi.h.
#define PAPI_VENDOR_INTEL 1
Definition at line 132 of file papi.h.
#define PAPI_VENDOR_UNKNOWN -1
Definition at line 131 of file papi.h.
#define PAPI_VER_CURRENT (PAPI_VERSION & 0xffffff00)
Definition at line 44 of file papi.h.
Referenced by init_PAPI().
#define PAPI_VERB_ECONT 1 /* Option to automatically report any return codes < 0 to stderr and continue. */
Definition at line 180 of file papi.h.
#define PAPI_VERB_ESTOP 2 /* Option to automatically report any return codes < 0 to stderr and exit. */
Definition at line 181 of file papi.h.
#define PAPI_VERSION PAPI_VERSION_NUMBER(3,0,7)
Definition at line 43 of file papi.h.
#define PAPI_VERSION_MAJOR (x) (((x)>>16) & 0xffff)
Definition at line 38 of file papi.h.
#define PAPI_VERSION_MINOR (x) (((x)>>8) & 0xff)
Definition at line 39 of file papi.h.
#define PAPI_VERSION_NUMBER (maj, min, rev) (((maj)<<16) | ((min)<<8) | (rev))
Definition at line 37 of file papi.h.
#define PAPI_VERSION_REVISION (x) ((x) & 0xff)
Definition at line 40 of file papi.h.
#define u_long_long unsigned long long
Definition at line 295 of file papi.h.
Typedef Documentation
typedef struct _papi_address_map PAPI_address_map_t
typedef int(* PAPI_debug_handler_t)(int code)
Definition at line 366 of file papi.h.
typedef struct _papi_debug_option PAPI_debug_option_t
typedef struct _papi_domain_option PAPI_domain_option_t
typedef struct event_info PAPI_event_info_t
typedef struct _papi_program_info PAPI_exe_info_t
typedef struct _papi_granularity_option PAPI_granularity_option_t
typedef struct _papi_hw_info PAPI_hw_info_t
typedef struct _papi_inherit_option PAPI_inherit_option_t
typedef struct _papi_mh_cache_info PAPI_mh_cache_info_t
typedef struct _papi_mh_info PAPI_mh_info_t
typedef struct _papi_mh_level_info PAPI_mh_level_t
typedef struct _papi_mh_tlb_info PAPI_mh_tlb_info_t
typedef struct _papi_multiplex_option PAPI_multiplex_option_t
typedef void(* PAPI_overflow_handler_t)(int EventSet, void *address, long_long overflow_vector, void *context)
Definition at line 312 of file papi.h.
typedef struct _papi_overflow_option PAPI_overflow_option_t
typedef struct _papi_preload_option PAPI_preload_info_t
typedef struct _papi_shared_lib_info PAPI_shlib_info_t
typedef struct _papi_sprofil PAPI_sprofil_t
typedef struct _papi_substrate_option PAPI_substrate_info_t
Enumeration Type Documentation
anonymous enum
Enumerator
PAPI_ENUM_ALL
PAPI_PRESET_ENUM_AVAIL
PAPI_PRESET_ENUM_INS
PAPI_PRESET_ENUM_BR
PAPI_PRESET_ENUM_MEM
PAPI_PRESET_ENUM_TLB
PAPI_PRESET_ENUM_FP
PAPI_PENT4_ENUM_GROUPS
PAPI_PENT4_ENUM_COMBOS
PAPI_PENT4_ENUM_BITS
PAPI_PWR4_ENUM_GROUPS
Definition at line 246 of file papi.h.
Function Documentation
void get_results ()
Definition at line 70 of file PAPI.cpp.
References Freq, get_time_stamp(), ID, TIME, and Value.
long long int getEmpty (int * , long long int *)
Definition at line 30 of file PAPI.cpp.
References PAPI_start_counters(), and PAPI_stop_counters().
Referenced by get_time_stamp(), init_PAPI(), and start_measures().
void init_PAPI (int)
Definition at line 37 of file PAPI.cpp.
References Events, Freq, getEmpty(), PAPI_library_init(), PAPI_VER_CURRENT, SIZE, Value, and Values.
int PAPI_accum (int EventSet, long_long * values)
int PAPI_accum_counters (long_long * values, int array_len)
int PAPI_add_event (int EventSet, int Event)
int PAPI_add_events (int EventSet, int * Events, int number)
int PAPI_cleanup_eventset (int EventSet)
int PAPI_create_eventset (int * EventSet)
int PAPI_destroy_eventset (int * EventSet)
int PAPI_enum_event (int * EventCode, int modifier)
int PAPI_event_code_to_name (int EventCode, char * out)
int PAPI_event_name_to_code (char * in, int * out)
int PAPI_flips (float * rtime, float * ptime, long_long * flpins, float * mflips)
int PAPI_flops (float * rtime, float * ptime, long_long * flpops, float * mflops)
int PAPI_get_event_info (int EventCode, PAPI_event_info_t * info)
const PAPI_exe_info_t* PAPI_get_executable_info (void)
const PAPI_hw_info_t* PAPI_get_hardware_info (void)
int PAPI_get_multiplex (int EventSet)
int PAPI_get_opt (int option, PAPI_option_t * ptr)
int PAPI_get_overflow_event_index (int Eventset, long_long overflow_vector, int * array, int * number)
long_long PAPI_get_real_cyc (void)
long_long PAPI_get_real_usec (void)
const PAPI_shlib_info_t* PAPI_get_shared_lib_info (void)
int PAPI_get_thr_specific (int tag, void ** ptr)
long_long PAPI_get_virt_cyc (void)
long_long PAPI_get_virt_usec (void)
int PAPI_ipc (float * rtime, float * ptime, long_long * ins, float * ipc)
int PAPI_is_initialized (void)
int PAPI_library_init (int version)
Referenced by init_PAPI().
int PAPI_list_events (int EventSet, int * Events, int * number)
int PAPI_lock (int)
int PAPI_multiplex_init (void)
int PAPI_num_counters (void)
int PAPI_num_events (int EventSet)
int PAPI_num_hwctrs (void)
int PAPI_overflow (int EventSet, int EventCode, int threshold, int flags, PAPI_overflow_handler_t handler)
int PAPI_perror (int code, char * destination, int length)
int PAPI_profil (void * buf, unsigned bufsiz, caddr_t offset, unsigned scale, int EventSet, int EventCode, int threshold, int flags)
int PAPI_query_event (int EventCode)
int PAPI_read (int EventSet, long_long * values)
int PAPI_read_counters (long_long * values, int array_len)
int PAPI_register_thread (void)
int PAPI_remove_event (int EventSet, int EventCode)
int PAPI_remove_events (int EventSet, int * Events, int number)
int PAPI_reset (int EventSet)
int PAPI_set_debug (int level)
int PAPI_set_domain (int domain)
int PAPI_set_granularity (int granularity)
int PAPI_set_multiplex (int EventSet)
int PAPI_set_opt (int option, PAPI_option_t * ptr)
int PAPI_set_thr_specific (int tag, void * ptr)
void PAPI_shutdown (void)
int PAPI_sprofil (PAPI_sprofil_t * prof, int profcnt, int EventSet, int EventCode, int threshold, int flags)
int PAPI_start (int EventSet)
int PAPI_start_counters (int * events, int array_len)
Referenced by getEmpty(), and start_measures().
int PAPI_state (int EventSet, int * status)
int PAPI_stop (int EventSet, long_long * values)
int PAPI_stop_counters (long_long * values, int array_len)
Referenced by get_time_stamp(), and getEmpty().
char* PAPI_strerror (int)
unsigned long PAPI_thread_id (void)
int PAPI_thread_init (unsigned long int(*)(void) id_fn)
int PAPI_unlock (int)
int PAPI_unregister_thread (void)
int PAPI_write (int EventSet, long_long * values)
void print_results ()
Definition at line 75 of file PAPI.cpp.
References Freq, SIZE, and Value.
void start_measures (int)
Definition at line 61 of file PAPI.cpp.
References Empty, Events, Freq, getEmpty(), ID, PAPI_start_counters(), TIME, and Values.
Variable Documentation
long long int Empty
Definition at line 21 of file papi.h.
Referenced by get_time_stamp(), and start_measures().
int Events[2]
Definition at line 19 of file papi.h.
Referenced by get_time_stamp(), init_PAPI(), and start_measures().
long long int Values[2]
Definition at line 20 of file papi.h.
Referenced by get_time_stamp(), init_PAPI(), and start_measures().