GEOS - Guide to Exploration of Otimization's Sequences: Test.cpp File Reference
Test.cpp File Reference
This file contains implementation of the GEOS's main functions. Which are responsable for interfacing heuristics that want to explore, in a fast way, the otmization's space set.
#include "GEOS.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include <stack>
#include <limits>
#include <random>
Functions
static cl::opt< std::string > LLVMFilename ("llvm-file", cl::desc("LLVM file to do time analysis"), cl::value_desc("filename.ll"), cl::Required)
static cl::alias llAlias ("ll", cl::desc("Alias for -llvm-file"), cl::aliasopt(LLVMFilename))
static cl::list< std::string > GCNOFilename ("gcno", cl::desc("One or more GCOV GCNO files"), cl::value_desc("filename.gcno"), cl::OneOrMore)
static cl::alias goAlias ("go", cl::desc("Alias for -gcno"), cl::aliasopt(GCNOFilename))
static cl::list< std::string > GCDAFilename ("gcda", cl::desc("One or more GCOV GCDA files"), cl::value_desc("filename.gcda"), cl::OneOrMore)
static cl::alias gaAlias ("ga", cl::desc("Alias for -gcda"), cl::aliasopt(GCDAFilename))
static cl::opt
< AnalysisMethodKind > OptAnalysisMethod (cl::desc("Choose an analysis method:"), cl::values(clEnumVal(instM,"Basic blocks are weighed by their number of instruction"), clEnumVal(instCostM,"Basic blocks are weighed by the sum up of all instruction cost"), clEnumVal(hashWM,"Basic blocks are weighed by similar basic block where which dimension has also a weight in the DB"), clEnumVal(randM,"Basic blocks are weighed randomicly"), clEnumVal(freqM,"No weight to basic blocks"), clEnumVal(hashPlusInstM,"Sum of the inst weight and hash weight"), clEnumValEnd))
static cl::opt< std::string > DatabaseFilename ("database", cl::desc("Hashs database to hashM analysis"), cl::value_desc("filename"))
static cl::alias dbAlias ("db", cl::desc("Alias for -database"), cl::aliasopt(DatabaseFilename))
static cl::opt< double > CPUFreq ("cpu-freq", cl::desc("defines CPU Clock rate."), cl::value_desc("CPU Clock"), cl::Required)
static cl::alias CPUAlias ("f", cl::desc("Alias for -cpu-freq"), cl::aliasopt(CPUFreq))
void printModule (ProfileModule *P, int Id)
int main (int argc, char **argv)
Detailed Description
This file contains implementation of the GEOS's main functions. Which are responsable for interfacing heuristics that want to explore, in a fast way, the otmization's space set.
Definition in file Test.cpp.
Function Documentation
static cl::alias CPUAlias ("f" , cl:: desc"Alias for -cpu-freq", cl:: aliasoptCPUFreq) static
static cl::opt<double> CPUFreq ("cpu-freq" , cl:: desc"defines CPU Clock rate.", cl:: value_desc"CPU Clock", cl::Required) static
Referenced by main().
static cl::opt<std::string> DatabaseFilename ("database" , cl:: desc"Hashs database to hashM analysis", cl:: value_desc"filename") static
Referenced by main().
static cl::alias dbAlias ("db" , cl:: desc"Alias for -database", cl:: aliasoptDatabaseFilename) static
static cl::alias gaAlias ("ga" , cl:: desc"Alias for -gcda", cl:: aliasoptGCDAFilename) static
static cl::list<std::string> GCDAFilename ("gcda" , cl:: desc"One or more GCOV GCDA files", cl:: value_desc"filename.gcda", cl::OneOrMore) static
Referenced by main().
static cl::list<std::string> GCNOFilename ("gcno" , cl:: desc"One or more GCOV GCNO files", cl:: value_desc"filename.gcno", cl::OneOrMore) static
Referenced by main().
static cl::alias goAlias ("go" , cl:: desc"Alias for -gcno", cl:: aliasoptGCNOFilename) static
static cl::alias llAlias ("ll" , cl:: desc"Alias for -llvm-file", cl:: aliasoptLLVMFilename) static
static cl::opt<std::string> LLVMFilename ("llvm-file" , cl:: desc"LLVM file to do time analysis", cl:: value_desc"filename.ll", cl::Required) static
Referenced by main().
int main (int argc, char ** argv)
Definition at line 85 of file Test.cpp.
References GEOS::analyseExecutionTime(), GEOS::applyPasses(), BreakCriticalEdges, CFGSimplification, CFGStructurization, CPUFreq(), DatabaseFilename(), FlattenCFG, GCDAFilename(), GCNOFilename(), GEOS::getAnalyser(), ProfileModule::getLLVMModule(), GEOS::getPass(), LLVMFilename(), LoadCombine, LoopDeletion, LoopSimplify, LoopStrengthReduce, LoopUnroll, OptAnalysisMethod(), and printModule().
static cl::opt<AnalysisMethodKind> OptAnalysisMethod (cl:: desc"Choose an analysis method:", cl:: valuesclEnumVal(instM,"Basic blocks are weighed by their number of instruction"), clEnumVal(instCostM,"Basic blocks are weighed by the sum up of all instruction cost"), clEnumVal(hashWM,"Basic blocks are weighed by similar basic block where which dimension has also a weight in the DB"), clEnumVal(randM,"Basic blocks are weighed randomicly"), clEnumVal(freqM,"No weight to basic blocks"), clEnumVal(hashPlusInstM,"Sum of the inst weight and hash weight"), clEnumValEnd) static
Referenced by main().
void printModule (ProfileModule * P, int Id)
Definition at line 74 of file Test.cpp.
References ProfileModule::getLLVMModule().
Referenced by main().