GEOS - Guide for Exploration of the Optimization Space: ProfileModule Class Reference
ProfileModule Class Reference
This class is responsible for encapsulating profile information with LLVM code, make copies of itself, and maintain the consistency of itself.
#include <ProfileModule.h>
Public Member Functions
PassSequence getPasses ()
If this class has been optimized this function will return the optimizations used.
void setPasses (PassSequence P)
Don't use this function. It is supposed to be used by the profile module.
void repairFunctionProfiling (llvm::Function *)
For each basic block in the CFG of the given function, its predecessors and successors are used to estimate and update its execution frequency.
void repairProfiling ()
Repair each function in the module.
bool hasBasicBlockFrequency (const llvm::BasicBlock &) const
Return true if the execution frequency of the given basic block is known, otherwise returns false.
uint64_t getBasicBlockFrequency (const llvm::BasicBlock &) const
Returns the execution frequency of the given basic block, but if it doesn't have the frequency, it will return 0.
void setBasicBlockFrequency (llvm::BasicBlock &, uint64_t)
Sets the execution frequency of a basic block.
bool hasBranchFrequency (const llvm::BasicBlock &) const
If the basic block ends with a branch as terminator instruction and the frequencies of this branch are known, it will return true. Otherwise, it will return false.
std::vector< uint32_t > getBranchFrequency (const llvm::BasicBlock &) const
Returns a vector with the execution frequency for each possible path that can be taken by the terminator instruction of a given basicblock. If it doesn't have the frequency it will return 0.
void setBranchFrequency (llvm::BasicBlock &, std::vector< uint32_t > &)
Sets the execution frequency for each path that can be taken by the terminator instruction of the given basicblock.
bool hasID (const llvm::Instruction &I) const
Returns true if the instruction have an ID, otherwise returns false.
int getID (const llvm::Instruction &I)
Returns the ID of a given instruction.
bool hasCallCost (const llvm::CallInst &) const
Returns true if the call instruction have a cost, otherwise returns false.
double getCallCost (const llvm::CallInst &) const
Returns the call cost of a given call instruction.
void setCallCost (llvm::CallInst &, double)
Sets the cost of a given call instruction.
ProfileModule (llvm::Module *)
llvm::Module * getLLVMModule () const
Returns its LLVM Module.
ProfileModule * getCopy () const
Make a copy of the Profiling Module.
void print (const std::string) const
It saves the LLVM module with all the profiling information in the given path.
Detailed Description
This class is responsible for encapsulating profile information with LLVM code, make copies of itself, and maintain the consistency of itself.
Definition at line 26 of file ProfileModule.h.
Constructor & Destructor Documentation
ProfileModule::ProfileModule (llvm::Module *)
Definition at line 69 of file ProfileModule.cpp.
References nC, and setID().
Member Function Documentation
uint64_t ProfileModule::getBasicBlockFrequency (const llvm::BasicBlock &) const
Returns the execution frequency of the given basic block, but if it doesn't have the frequency, it will return 0.
Definition at line 119 of file ProfileModule.cpp.
References BBFreq.
Referenced by StaticInstructionAnalysis::estimateCost(), TTIInstructionAnalysis::estimateCost(), BranchAnalysis::estimateCost(), CallAnalysis::estimateCost(), RandomAnalysis::estimateCost(), and spreadOverCallGraph().
std::vector< uint32_t > ProfileModule::getBranchFrequency (const llvm::BasicBlock &) const
Returns a vector with the execution frequency for each possible path that can be taken by the terminator instruction of a given basicblock. If it doesn't have the frequency it will return 0.
Definition at line 101 of file ProfileModule.cpp.
double ProfileModule::getCallCost (const llvm::CallInst &) const
Returns the call cost of a given call instruction.
Definition at line 136 of file ProfileModule.cpp.
References getWeight().
Referenced by CallAnalysis::estimateCost().
ProfileModule * ProfileModule::getCopy () const
Make a copy of the Profiling Module.
Definition at line 265 of file ProfileModule.cpp.
Referenced by GEOS::applyPasses(), and JITExecution::JITExecution().
int ProfileModule::getID (const llvm::Instruction & I)
Returns the ID of a given instruction.
Definition at line 54 of file ProfileModule.cpp.
Referenced by loadCallCost().
Module * ProfileModule::getLLVMModule () const
Returns its LLVM Module.
Definition at line 83 of file ProfileModule.cpp.
Referenced by GEOS::applyPasses(), StaticInstructionAnalysis::estimateCost(), TTIInstructionAnalysis::estimateCost(), BranchAnalysis::estimateCost(), CallAnalysis::estimateCost(), RandomAnalysis::estimateCost(), CostEstimator::getModuleCost(), InstructionCacheAnalysis::InstructionCacheAnalysis(), JITExecution::JITExecution(), loadCallCost(), loadGCOV(), loadStaticProfiling(), RegisterUseAnalysis::RegisterUseAnalysis(), and spreadOverCallGraph().
PassSequence ProfileModule::getPasses () inline
If this class has been optimized this function will return the optimizations used.
Definition at line 41 of file ProfileModule.h.
bool ProfileModule::hasBasicBlockFrequency (const llvm::BasicBlock &) const
Return true if the execution frequency of the given basic block is known, otherwise returns false.
Definition at line 115 of file ProfileModule.cpp.
References BBFreq.
bool ProfileModule::hasBranchFrequency (const llvm::BasicBlock &) const
If the basic block ends with a branch as terminator instruction and the frequencies of this branch are known, it will return true. Otherwise, it will return false.
Definition at line 89 of file ProfileModule.cpp.
bool ProfileModule::hasCallCost (const llvm::CallInst &) const
Returns true if the call instruction have a cost, otherwise returns false.
Definition at line 132 of file ProfileModule.cpp.
References hasWeight().
bool ProfileModule::hasID (const llvm::Instruction & I) const
Returns true if the instruction have an ID, otherwise returns false.
Definition at line 50 of file ProfileModule.cpp.
Referenced by loadCallCost().
void ProfileModule::print (const std::string Path) const
It saves the LLVM module with all the profiling information in the given path.
Definition at line 270 of file ProfileModule.cpp.
Referenced by GEOS::applyPasses().
void ProfileModule::repairFunctionProfiling (llvm::Function *)
For each basic block in the CFG of the given function, its predecessors and successors are used to estimate and update its execution frequency.
Definition at line 219 of file ProfileModule.cpp.
void ProfileModule::repairProfiling ()
Repair each function in the module.
Definition at line 245 of file ProfileModule.cpp.
Referenced by GEOS::applyPasses().
void ProfileModule::setBasicBlockFrequency (llvm::BasicBlock & , uint64_t)
Sets the execution frequency of a basic block.
Definition at line 128 of file ProfileModule.cpp.
References BBFreq, and Freq.
Referenced by loadGCOV(), and spreadOverCallGraph().
void ProfileModule::setBranchFrequency (llvm::BasicBlock & , std::vector< uint32_t > &)
Sets the execution frequency for each path that can be taken by the terminator instruction of the given basicblock.
Definition at line 94 of file ProfileModule.cpp.
Referenced by loadGCOV().
void ProfileModule::setCallCost (llvm::CallInst & , double)
Sets the cost of a given call instruction.
Definition at line 143 of file ProfileModule.cpp.
References setWeight().
Referenced by loadCallCost().
void ProfileModule::setPasses (PassSequence P) inline
Don't use this function. It is supposed to be used by the profile module.
Definition at line 47 of file ProfileModule.h.
Referenced by GEOS::applyPasses().
The documentation for this class was generated from the following files:
ProfileModule.h
ProfileModule.cpp