GEOS - Guide for Exploration of the Optimization Space: StaticInstructionAnalysis Class Reference
StaticInstructionAnalysis Class Reference
Return the sum of the cost of all LLVM instruction multiplicated by its the execution frequency. The cost is the same for every architecture.
#include <CostAnalysis.h>
Public Member Functions
double estimateCost (llvm::StringRef, const ProfileModule *, CostEstimatorOptions) const
This is a interface for implementation of a function for analysis the cost a function.
Detailed Description
Return the sum of the cost of all LLVM instruction multiplicated by its the execution frequency. The cost is the same for every architecture.
Definition at line 48 of file CostAnalysis.h.
Member Function Documentation
double StaticInstructionAnalysis::estimateCost (llvm::StringRef , const ProfileModule * , CostEstimatorOptions) const virtual
This is a interface for implementation of a function for analysis the cost a function.
Parameters
The parameters are the name of the function, the ProfileModule, and the options.
Implements CostAnalysis.
Definition at line 21 of file StaticCostEstimator.cpp.
References ProfileModule::getBasicBlockFrequency(), InstructionCostEstimator::getInstructionCost(), and ProfileModule::getLLVMModule().
The documentation for this class was generated from the following files:
CostAnalysis.h
StaticCostEstimator.cpp