GEOS - Guide for Exploration of the Optimization Space: InstructionCacheAnalysis Class Reference
InstructionCacheAnalysis Class Reference
#include <CostAnalysis.h>
Public Member Functions
InstructionCacheAnalysis (const ProfileModule *)
~InstructionCacheAnalysis ()
double estimateCost (llvm::StringRef, const ProfileModule *, CostEstimatorOptions) const
This is a interface for implementation of a function for analysis the cost a function.
Detailed Description
This analyis method estimate the cost of the instruction's cache. Due to the fact that it is necessery to compile the LLVM code to the machine assembly, so it can be expensive.
Definition at line 49 of file CostAnalysis.h.
Constructor & Destructor Documentation
InstructionCacheAnalysis::InstructionCacheAnalysis (const ProfileModule * P)
Definition at line 245 of file InstructionCacheAnalysis.cpp.
References MachineAST::getFunctionCost(), ProfileModule::getLLVMModule(), loadCodeGenPasses(), MAST, and PM.
InstructionCacheAnalysis::~InstructionCacheAnalysis ()
Definition at line 256 of file InstructionCacheAnalysis.cpp.
References MAST, and PM.
Member Function Documentation
double InstructionCacheAnalysis::estimateCost (llvm::StringRef , const ProfileModule * , CostEstimatorOptions) const virtual
This is a interface for implementation of a function for analysis the cost a function.
Parameters
The parameters are the name of the function, the ProfileModule, and the options.
Implements CostAnalysis.
Definition at line 261 of file InstructionCacheAnalysis.cpp.
References MachineAST::getFunctionCost(), and MAST.
The documentation for this class was generated from the following files:
CostAnalysis.h
InstructionCacheAnalysis.cpp