GEOS - Guide for Exploration of the Optimization Space: PassSequence Class Reference
PassSequence Class Reference
The aim of this class is to manage a sequence of optimizations.
#include <PassSequence.h>
Public Types
typedef std::vector
< OptimizationKind >::iterator iterator
typedef std::vector
< OptimizationKind >
::const_iterator const_iterator
Public Member Functions
void setOLevel (OptLevel OL)
void setOSize (OptLevel OS)
void add (OptimizationKind P)
Inserts at the end an Optimization.
void randomize (unsigned NumOfOptimizations, bool RandomSize=false, OptLevel OL=None, OptLevel OS=None)
Populate the PassSequence with randomics optimizations.
void populatePassManager (llvm::PassManager &PM, llvm::FunctionPassManager &FPM)
unsigned size () const
void print ()
PassSequence crossOver (const PassSequence &Rhs) const
Returns an mix between both PassSequences with the same size. With 50% of chance for each pass to be from the first or se second sequence.
PassSequence operator* (const PassSequence &Rhs) const
Same as crossOver.
PassSequence operator+ (const PassSequence &Rhs) const
Add all the sequences from the second into the first.
bool operator== (const PassSequence &Rhs) const
Returns true if both sequences have the same passes and in the same order.
bool operator!= (const PassSequence &Rhs) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Detailed Description
The aim of this class is to manage a sequence of optimizations.
Definition at line 86 of file PassSequence.h.
Member Typedef Documentation
typedef std::vector<OptimizationKind>::const_iterator PassSequence::const_iterator
Definition at line 332 of file PassSequence.h.
typedef std::vector<OptimizationKind>::iterator PassSequence::iterator
Definition at line 331 of file PassSequence.h.
Member Function Documentation
void PassSequence::add (OptimizationKind P) inline
Inserts at the end an Optimization.
Definition at line 225 of file PassSequence.h.
References LoopIdiom, LoopReroll, and LoopRotate.
Referenced by crossOver(), operator+(), and randomize().
iterator PassSequence::begin () inline
Definition at line 333 of file PassSequence.h.
Referenced by crossOver(), and operator==().
const_iterator PassSequence::begin () const inline
Definition at line 334 of file PassSequence.h.
PassSequence PassSequence::crossOver (const PassSequence & Rhs) const inline
Returns an mix between both PassSequences with the same size. With 50% of chance for each pass to be from the first or se second sequence.
Definition at line 283 of file PassSequence.h.
References add(), and begin().
Referenced by operator*().
iterator PassSequence::end () inline
Definition at line 335 of file PassSequence.h.
const_iterator PassSequence::end () const inline
Definition at line 336 of file PassSequence.h.
bool PassSequence::operator!= (const PassSequence & Rhs) const inline
Definition at line 327 of file PassSequence.h.
PassSequence PassSequence::operator* (const PassSequence & Rhs) const inline
Same as crossOver.
Definition at line 299 of file PassSequence.h.
References crossOver().
PassSequence PassSequence::operator+ (const PassSequence & Rhs) const inline
Add all the sequences from the second into the first.
Definition at line 304 of file PassSequence.h.
References add().
bool PassSequence::operator== (const PassSequence & Rhs) const inline
Returns true if both sequences have the same passes and in the same order.
Definition at line 315 of file PassSequence.h.
References begin(), and size().
void PassSequence::populatePassManager (llvm::PassManager & PM, llvm::FunctionPassManager & FPM) inline
Definition at line 249 of file PassSequence.h.
Referenced by GEOS::applyPasses().
void PassSequence::print () inline
Definition at line 268 of file PassSequence.h.
void PassSequence::randomize (unsigned NumOfOptimizations, bool RandomSize = false, OptLevel OL = None, OptLevel OS = None) inline
Populate the PassSequence with randomics optimizations.
Parameters
RandomSize when set as true make the function generate sequences with size in the range between 1 to NumOfOptimizations.
Definition at line 236 of file PassSequence.h.
References add(), Random, setOLevel(), and setOSize().
void PassSequence::setOLevel (OptLevel OL) inline
Definition at line 216 of file PassSequence.h.
Referenced by randomize().
void PassSequence::setOSize (OptLevel OS) inline
Definition at line 220 of file PassSequence.h.
Referenced by randomize().
unsigned PassSequence::size () const inline
Definition at line 264 of file PassSequence.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
PassSequence.h