GEOS - Guide for Exploration of the Optimization Space: GEOSCommandLineParser.h File Reference
GEOSCommandLineParser.h File Reference
#include "llvm/Support/CommandLine.h"
#include "CostEstimator/CostEstimatorOptions.h"
#include "Profiling/GCOVReader.h"
#include "Profiling/StaticProfiling.h"
#include "Profiling/CallCostReader.h"
Namespaces
gcl
Functions
static cl::opt< std::string > LLVMFilename ("llvm-file", cl::desc("LLVM file to do time analysis"), cl::value_desc("filename.ll"), cl::Required)
static cl::alias llAlias ("ll", cl::desc("Alias for -llvm-file"), cl::aliasopt(LLVMFilename))
static cl::list< std::string > GCNOFilename ("gcno", cl::desc("One or more GCOV GCNO files"), cl::value_desc("filename.gcno"), cl::ZeroOrMore)
static cl::alias goAlias ("go", cl::desc("Alias for -gcno"), cl::aliasopt(GCNOFilename))
static cl::list< std::string > GCDAFilename ("gcda", cl::desc("One or more GCOV GCDA files"), cl::value_desc("filename.gcda"), cl::ZeroOrMore)
static cl::alias gaAlias ("ga", cl::desc("Alias for -gcda"), cl::aliasopt(GCDAFilename))
static cl::opt< double > CPUFreq ("cpu-freq", cl::desc("defines CPU Clock rate."), cl::value_desc("CPU Clock"))
static cl::alias CPUAlias ("f", cl::desc("Alias for -cpu-freq"), cl::aliasopt(CPUFreq))
static cl::opt< double > BranchFreq ("-branch-freq", cl::desc("defines branch misprediction rate."), cl::value_desc("branch misprediction frequency"))
static cl::alias BFAlias ("brf", cl::desc("alias for -branch-freq"), cl::aliasopt(BranchFreq))
static cl::opt< double > BranchCost ("-branch-cost", cl::desc("defines branch misprediction cost."), cl::value_desc("branch misprediction cost"))
static cl::alias BCalias ("brc", cl::desc("alias for -branch-cost"), cl::aliasopt(BranchCost))
static cl::opt< std::string > CallCost ("-call", cl::desc("defines callcost file."), cl::value_desc("CallCost"))
static cl::alias CallCostAlias ("c", cl::desc("Alias for -call"), cl::aliasopt(CallCost))
static cl::list< CostAnalysisKind > Analysis (cl::desc("Choose one or more analysis method:"), cl::values(clEnumVal(InstructionCache,"Analyse register use cost."), clEnumVal(RegisterUse,"Analyse register use cost."), clEnumVal(StaticInstruction,"Analyse instruction costs using the same weight for each instruction independent of plataform."), clEnumVal(TTIInstruction,"Analyse instruction costs with weights that are plataform sensitive."), clEnumVal(Branch,"Analyse branch misprediction cost."), clEnumVal(Call,"Analyse extern call costs. (Need profiling)"), clEnumVal(RandomCost,"Random cost."), clEnumValEnd))
static cl::opt
< CostEstimatorOptionsSet > AnalysisSet (cl::desc("Choose an analysis set:"), cl::values(clEnumVal(NonArchSensitive,"Set of analysis that does't change for diferents architectures."), clEnumVal(ArchSensitive,"Set of analysis that does changes for diferents architectures."), clEnumValEnd))
void gcl::GEOSParseCommandLineOptions (int argc, char **argv)
CostEstimatorOptions & gcl::populatePModule (ProfileModule *PModule)
Function Documentation
static cl::list<CostAnalysisKind> Analysis (cl:: desc"Choose one or more analysis method:", cl:: valuesclEnumVal(InstructionCache,"Analyse register use cost."), clEnumVal(RegisterUse,"Analyse register use cost."), clEnumVal(StaticInstruction,"Analyse instruction costs using the same weight for each instruction independent of plataform."), clEnumVal(TTIInstruction,"Analyse instruction costs with weights that are plataform sensitive."), clEnumVal(Branch,"Analyse branch misprediction cost."), clEnumVal(Call,"Analyse extern call costs. (Need profiling)"), clEnumVal(RandomCost,"Random cost."), clEnumValEnd) static
Referenced by gcl::populatePModule().
static cl::opt<CostEstimatorOptionsSet> AnalysisSet (cl:: desc"Choose an analysis set:", cl:: valuesclEnumVal(NonArchSensitive,"Set of analysis that does't change for diferents architectures."), clEnumVal(ArchSensitive,"Set of analysis that does changes for diferents architectures."), clEnumValEnd) static
Referenced by gcl::populatePModule().
static cl::alias BCalias ("brc" , cl:: desc"alias for -branch-cost", cl:: aliasoptBranchCost) static
static cl::alias BFAlias ("brf" , cl:: desc"alias for -branch-freq", cl:: aliasoptBranchFreq) static
static cl::opt<double> BranchCost ("-branch-cost" , cl:: desc"defines branch misprediction cost.", cl:: value_desc"branch misprediction cost") static
Referenced by gcl::populatePModule().
static cl::opt<double> BranchFreq ("-branch-freq" , cl:: desc"defines branch misprediction rate.", cl:: value_desc"branch misprediction frequency") static
Referenced by loadGCOV(), and gcl::populatePModule().
static cl::opt<std::string> CallCost ("-call" , cl:: desc"defines callcost file.", cl:: value_desc"CallCost") static
Referenced by gcl::populatePModule().
static cl::alias CallCostAlias ("c" , cl:: desc"Alias for -call", cl:: aliasoptCallCost) static
static cl::alias CPUAlias ("f" , cl:: desc"Alias for -cpu-freq", cl:: aliasoptCPUFreq) static
static cl::opt<double> CPUFreq ("cpu-freq" , cl:: desc"defines CPU Clock rate.", cl:: value_desc"CPU Clock") static
Referenced by gcl::populatePModule().
static cl::alias gaAlias ("ga" , cl:: desc"Alias for -gcda", cl:: aliasoptGCDAFilename) static
static cl::list<std::string> GCDAFilename ("gcda" , cl:: desc"One or more GCOV GCDA files", cl:: value_desc"filename.gcda", cl::ZeroOrMore) static
Referenced by gcl::populatePModule().
static cl::list<std::string> GCNOFilename ("gcno" , cl:: desc"One or more GCOV GCNO files", cl:: value_desc"filename.gcno", cl::ZeroOrMore) static
Referenced by gcl::populatePModule().
static cl::alias goAlias ("go" , cl:: desc"Alias for -gcno", cl:: aliasoptGCNOFilename) static
static cl::alias llAlias ("ll" , cl:: desc"Alias for -llvm-file", cl:: aliasoptLLVMFilename) static
static cl::opt<std::string> LLVMFilename ("llvm-file" , cl:: desc"LLVM file to do time analysis", cl:: value_desc"filename.ll", cl::Required) static