GEOS - Guide for Exploration of the Optimization Space: gcl Namespace Reference
gcl Namespace Reference
Functions
void GEOSParseCommandLineOptions (int argc, char **argv)
CostEstimatorOptions & populatePModule (ProfileModule *PModule)
Function Documentation
void gcl::GEOSParseCommandLineOptions (int argc, char ** argv)
Definition at line 76 of file GEOSCommandLineParser.h.
CostEstimatorOptions& gcl::populatePModule (ProfileModule * PModule)
Definition at line 80 of file GEOSCommandLineParser.h.
References Analysis(), AnalysisSet(), BranchCost(), BranchFreq(), CallCost(), CPUFreq(), GCDAFilename(), GCNOFilename(), loadCallCost(), loadGCOV(), and loadStaticProfiling().