GEOS - Guide for Exploration of the Optimization Space: ProfileModule.cpp File Reference
ProfileModule.cpp File Reference
This file contains implementation of the ProfileModule, which encapsulate a LLVMModule and its profiling information.
#include "ProfileModule/ProfileModule.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <unordered_map>
Classes
struct StaticProfiling
Functions
bool hasWeight (const Instruction &I)
double getWeight (const Instruction &I)
void setWeight (Instruction &I, double Weight)
void setID (Instruction &I, int ID)
Variables
int nC = 0
std::unordered_map
< std::string, uint64_t > BBFreq
Detailed Description
This file contains implementation of the ProfileModule, which encapsulate a LLVMModule and its profiling information.
Definition in file ProfileModule.cpp.
Function Documentation
double getWeight (const Instruction & I)
Definition at line 35 of file ProfileModule.cpp.
References hasWeight().
Referenced by ProfileModule::getCallCost().
bool hasWeight (const Instruction & I)
Definition at line 31 of file ProfileModule.cpp.
Referenced by getWeight(), and ProfileModule::hasCallCost().
void setID (Instruction & I, int ID)
Definition at line 61 of file ProfileModule.cpp.
Referenced by ProfileModule::ProfileModule().
void setWeight (Instruction & I, double Weight)
Definition at line 43 of file ProfileModule.cpp.
Referenced by ProfileModule::setCallCost().
Variable Documentation
std::unordered_map<std::string, uint64_t> BBFreq
Definition at line 87 of file ProfileModule.cpp.
Referenced by ProfileModule::getBasicBlockFrequency(), ProfileModule::hasBasicBlockFrequency(), and ProfileModule::setBasicBlockFrequency().
int nC = 0
Definition at line 68 of file ProfileModule.cpp.
Referenced by ProfileModule::ProfileModule().