GEOS - Guide for Exploration of the Optimization Space: StaticProfiling.cpp File Reference
StaticProfiling.cpp File Reference
#include "Profiling/StaticProfiling.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/PassManager.h"
#include "llvm/Pass.h"
#include <list>
#include <unordered_map>
Classes
struct StaticProfiling
Enumerations
enum Mark { Temporary, Permanent, None }
Functions
void visit (CallGraphNode &CallNode, std::unordered_map< Function *, Mark > &Marks, std::list< Function * > &SortedList)
bool isUnmarked (std::pair< Function *, Mark > Elem)
std::list< Function * > & topologicalSort (CallGraph &CG)
void spreadOverCallGraph (ProfileModule *Profile)
void loadStaticProfiling (ProfileModule *Profile)
This function estimate the execution frequency of each branch and add this information in the Profile Module.
Enumeration Type Documentation
enum Mark
Enumerator
Temporary
Permanent
None
Definition at line 52 of file StaticProfiling.cpp.
Function Documentation
bool isUnmarked (std::pair< Function *, Mark > Elem)
Definition at line 75 of file StaticProfiling.cpp.
References None.
Referenced by topologicalSort().
void loadStaticProfiling (ProfileModule * Profile)
This function estimate the execution frequency of each branch and add this information in the Profile Module.
Definition at line 130 of file StaticProfiling.cpp.
References ProfileModule::getLLVMModule(), PM, and spreadOverCallGraph().
void spreadOverCallGraph (ProfileModule * Profile)
Definition at line 95 of file StaticProfiling.cpp.
References ProfileModule::getBasicBlockFrequency(), ProfileModule::getLLVMModule(), ProfileModule::setBasicBlockFrequency(), and topologicalSort().
Referenced by loadStaticProfiling().
std::list<Function*>& topologicalSort (CallGraph & CG)
Definition at line 79 of file StaticProfiling.cpp.
References isUnmarked(), None, and visit().
Referenced by spreadOverCallGraph().
void visit (CallGraphNode & CallNode, std::unordered_map< Function *, Mark > & Marks, std::list< Function * > & SortedList)
Definition at line 54 of file StaticProfiling.cpp.
References None, Permanent, and Temporary.
Referenced by topologicalSort().